name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  project:
    name: Project Checks
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v3
      with:
        path: src/github.com/containerd/fuse-overlayfs-snapshotter
        fetch-depth: 25
    - uses: containerd/project-checks@v1
      with:
        working-directory: src/github.com/containerd/fuse-overlayfs-snapshotter

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        fuse-overlayfs: [v1.0.0, v1.9, main]
    env:
      FUSEOVERLAYFS_COMMIT: "${{ matrix.fuse-overlayfs }}"
    steps:
    - uses: actions/checkout@v3
    - run: make test

  cross:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v3
    - run: make artifacts
